// Generated by scripts/embed_templates.py — do not edit by hand.
#include "needle/rules/templates.h"

#include <cstring>

namespace needle {
namespace templates {
namespace {

const char* const kTpl_goal_gate =
R"TEMPLATE(digraph goal_gate {
    // Goal gate: implement has goal_gate=true, validate checks quality

    start [shape=Mdiamond, label="Start"];
    implement [shape=box, label="Implement", prompt="Write a robust implementation", goal_gate="true"];
    validate [shape=box, label="Validate", prompt="Run tests and check coverage"];
    exit [shape=Msquare, label="Done"];

    start -> implement;
    implement -> validate;
    validate -> exit [label="pass", condition="outcome=success"];
    validate -> implement [label="fail", condition="outcome=failure"];
}
)TEMPLATE";

const char* const kTpl_human_gate =
R"TEMPLATE(digraph human_gate {
    // Human-in-the-loop: implement -> review (human) -> exit or -> fix -> review loop

    start [shape=Mdiamond, label="Start"];
    implement [shape=box, label="Implement", prompt="Write the initial implementation"];
    review [shape=hexagon, label="Code Review", prompt="Review the implementation"];
    fix [shape=box, label="Fix Issues", prompt="Fix the issues found in review"];
    exit [shape=Msquare, label="Done"];

    start -> implement;
    implement -> review;
    review -> exit [label="Approve"];
    review -> fix [label="Reject"];
    fix -> review;
}
)TEMPLATE";

const char* const kTpl_interactive_chat =
R"TEMPLATE(digraph interactive_chat {
    // Demonstrates the interactive handler: draft -> human-in-the-loop chat -> done.
    //
    // Run:    needle run sample_dots/interactive_chat.dot --var topic="distributed task queues"
    // Serve:  needle serve sample_dots/interactive_chat.dot
    //         (the dashboard opens a chat panel when the "review" node runs)

    graph [
        goal="Draft a short explainer and refine it with a human-in-the-loop chat.",
        label="Interactive chat demo",
        template="true",
        params="topic:text:required,
                mode:choice(interactive|autonomous):interactive"
    ];

    start [shape=Mdiamond, label="Start"];

    draft [shape=box, label="Draft explainer",
           prompt="Write a 6-8 sentence explainer on: $var.topic. Plain prose, no bullets."];

    review [handler="interactive", label="Review with human",
            mode="$var.mode",
            prompt="Here is the draft:\n\n$context.draft.output\n\nWork with the user to refine it. When they are satisfied, return the final version."];

    exit [shape=Msquare, label="Done"];

    start -> draft;
    draft -> review;
    review -> exit;
}
)TEMPLATE";

const char* const kTpl_multi_backend =
R"TEMPLATE(digraph multi_backend {
    // Mix of codergen (CLI backend) and llmkit (direct API) nodes

    start [shape=Mdiamond, label="Start"];
    plan [shape=box, label="Plan Architecture", handler="llmkit", prompt="Design the system architecture"];
    implement [shape=box, label="Implement Code", prompt="Implement the planned architecture"];
    review [shape=box, label="Review Code", handler="llmkit", prompt="Review the implementation for bugs"];
    exit [shape=Msquare, label="Done"];

    start -> plan;
    plan -> implement;
    implement -> review;
    review -> exit;
}
)TEMPLATE";

const char* const kTpl_parallel_pipeline =
R"TEMPLATE(digraph parallel_pipeline {
    // Parallel branches: start -> fork -> [branch_a, branch_b] -> join -> exit

    start [shape=Mdiamond, label="Start"];
    fork [shape=component, label="Fork"];
    branch_a [shape=box, label="Build Frontend", prompt="Build the frontend component"];
    branch_b [shape=box, label="Build Backend", prompt="Build the backend service"];
    join [shape=trapezium, label="Merge"];
    exit [shape=Msquare, label="Done"];

    start -> fork;
    fork -> branch_a;
    fork -> branch_b;
    branch_a -> join;
    branch_b -> join;
    join -> exit;
}
)TEMPLATE";

const char* const kTpl_reference_template =
R"TEMPLATE(// Reference template for an end-to-end project pipeline.
// Demonstrates the canonical attractor pattern; a meta-pipeline can
// point an LLM at this file and ask it to adapt the topology for a
// specific project. Not meant to be run directly.
//
// Canonical pattern:
//   orient → plan → implement (fan-out per module) → merge → validate ⟲ fix
//   → integration_test ⟲ fix → write_readme → review (human) → exit
//   review → apply_feedback → validate (feedback loop)

digraph ReferenceTemplate {
    graph [
        goal="$goal",
        label="$label",
        default_fidelity="compact",
        default_max_retries=3,
        retry_target="plan",
        model_stylesheet="
            * { agent = \"claude\"; llm_model = \"claude-sonnet-4-6\" }
            .planning { agent = \"claude\"; llm_model = \"claude-opus-4-7\"; reasoning_effort = \"high\" }
            .coding { agent = \"codex\"; llm_model = \"gpt-5.4\" }
            .critique { agent = \"gemini\"; llm_model = \"gemini-2.5-pro\" }
        "
    ]

    node [shape=box, timeout="30m"]

    // ═══════════════════════════════════════════════════════════════
    // TERMINALS
    // ═══════════════════════════════════════════════════════════════
    start [shape=Mdiamond, label="Start"]
    exit  [shape=Msquare,  label="Done"]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 1: ORIENT — assess workspace, tools, prior artifacts
    // ═══════════════════════════════════════════════════════════════
    orient [
        class="planning",
        label="Orient",
        fidelity="truncate",
        prompt="Assess the current workspace:\n1. Check language/toolchain versions\n2. Check for existing project structure\n3. Check for prior run artifacts ({{logs_dir}}/orient/*, {{logs_dir}}/implement/*, {{logs_dir}}/validate/*)\n4. List available tools and dependencies\n\nWrite findings to {{logs_dir}}/orient/ORIENT-{N}.md (next sequential number)."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 2: PLAN — architecture and implementation strategy
    // ═══════════════════════════════════════════════════════════════
    plan [
        class="planning",
        label="Plan",
        fidelity="summary:high",
        prompt="Read {{logs_dir}}/orient/ORIENT-*.md and any prior {{logs_dir}}/plan/PLAN-*.md.\n\nProduce a detailed implementation plan:\n1. Architecture overview\n2. Module breakdown with dependencies\n3. File structure\n4. Testing strategy\n5. Acceptance criteria\n\nWrite to {{logs_dir}}/plan/PLAN-{N}.md."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 3: IMPLEMENT — build the project
    // For large projects, decompose into parallel modules:
    //   implement_fan → {module_a, module_b, module_c} → merge_impl
    // Each module targets ~200-500 lines of new code.
    // ═══════════════════════════════════════════════════════════════
    implement [
        label="Implement",
        timeout="45m",
        fidelity="full",
        prompt="Read {{logs_dir}}/plan/PLAN-*.md. Check for prior {{logs_dir}}/implement/PROGRESS-*.md.\n\nImplement the plan. For each module:\n1. Write the code\n2. Write unit tests\n3. Verify it compiles\n\nWrite progress to {{logs_dir}}/implement/PROGRESS-{N}.md.\nCommit after each logical unit of work."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 4: VALIDATE — automated testing (validate-fix loop)
    // ═══════════════════════════════════════════════════════════════
    validate [
        label="Validate",
        handler="tool",
        goal_gate=true,
        retry_target="plan",
        command="echo 'Replace with: make test, cargo test, npm test, etc.'"
    ]

    fix [
        label="Fix",
        fidelity="summary:high",
        prompt="Read the validation output. Check {{logs_dir}}/validate/VALIDATION-RUN-*.md.\n\nFix all failures:\n1. Read the error messages carefully\n2. Fix the root cause (not just the symptom)\n3. Re-run the failing tests locally to verify\n\nCommit fixes."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 5: INTEGRATION TEST — behavioral validation
    // ═══════════════════════════════════════════════════════════════
    integration_test [
        label="Integration Test",
        handler="tool",
        goal_gate=true,
        retry_target="fix_integration",
        command="echo 'Replace with: behavioral test that runs the app and verifies output'"
    ]

    fix_integration [
        label="Fix Integration",
        fidelity="summary:high",
        prompt="Read the integration test output.\n\nFix integration failures. These are typically:\n- Missing API connections\n- Wrong endpoints or ports\n- UI not rendering data\n- Environment configuration issues\n\nCommit fixes."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 6: CRITIQUE — adversarial review by different model
    // ═══════════════════════════════════════════════════════════════
    critique [
        class="critique",
        label="Adversarial Critique",
        fidelity="summary:high",
        prompt="Review the full implementation. Be harsh. Look for:\n1. Security vulnerabilities\n2. Error handling gaps\n3. Edge cases not covered\n4. Performance issues\n5. Missing features from the goal\n6. Test coverage gaps\n\nWrite findings to {{logs_dir}}/critique/CRITIQUE-{N}.md.\nPrioritize: which issues actually matter vs which are nitpicks?"
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 7: DOCUMENTATION
    // ═══════════════════════════════════════════════════════════════
    write_readme [
        label="Write README",
        fidelity="compact",
        prompt="Write README.md with:\n1. Project description\n2. Prerequisites\n3. Build/install instructions\n4. How to run\n5. Usage examples\n6. Architecture overview\n\nThe README should give a new developer everything they need."
    ]

    // ═══════════════════════════════════════════════════════════════
    // PHASE 8: HUMAN REVIEW — approve or request changes
    // ═══════════════════════════════════════════════════════════════
    review [
        shape=hexagon,
        label="Review",
        prompt="All automated tests pass. The implementation has been critiqued and documented.\n\nOptions:\n- Approve: the project is complete\n- Request changes: describe what needs to be fixed"
    ]

    apply_feedback [
        label="Apply Feedback",
        fidelity="summary:high",
        prompt="The reviewer requested changes:\n$context.human.gate.feedback\n\nApply the requested changes and commit."
    ]

    // ═══════════════════════════════════════════════════════════════
    // EDGES
    // ═══════════════════════════════════════════════════════════════
    start -> orient -> plan -> implement -> validate

    // Validate-fix loop
    validate -> integration_test [label="pass", condition="outcome=success"]
    validate -> fix [label="fail", condition="outcome!=success"]
    fix -> validate

    // Integration-fix loop
    integration_test -> critique [label="pass", condition="outcome=success"]
    integration_test -> fix_integration [label="fail", condition="outcome!=success"]
    fix_integration -> integration_test

    // Post-critique documentation and review
    critique -> write_readme -> review

    // Human review: approve or request changes
    review -> exit [label="approve"]
    review -> apply_feedback [label="changes"]
    apply_feedback -> validate
}
)TEMPLATE";

const char* const kTpl_simple_pipeline =
R"TEMPLATE(digraph simple_pipeline {
    // Basic: start -> implement -> validate -> exit

    start [shape=Mdiamond, label="Start"];
    implement [shape=box, label="Implement Feature", prompt="Implement a hello world program in Python"];
    validate [shape=box, label="Validate Output", prompt="Check that the implementation is correct"];
    exit [shape=Msquare, label="Done"];

    start -> implement;
    implement -> validate;
    validate -> exit;
}
)TEMPLATE";

const char* const kTpl_troubleshoot_test_diagnose_only =
R"TEMPLATE(// Troubleshoot test fixture — Diagnose tier
//
// Failure shape:  SelfExitError with operator-judgement-required signal
//                 (deliberate exit code 42 + a "needs human" stderr message)
// Expected behavior: Diagnose mode reads the run artifacts, classifies the
//                 failure, writes a recovery report, and EITHER stops at
//                 `outcome: reported` OR escalates via `needle troubleshoot
//                 escalate --reason "<short>" --next-question "<short>"`.
// Definition of success: the run remains in `failed` state (no resume), a
//                 recovery.md appears under
//                 `<run-dir>/troubleshoot/session-*/recovery.md`, and the
//                 dashboard troubleshoot tile shows the report link.
//                 If escalated, the tile flips to the interactive chat
//                 surface.
//
// Drive it: see README troubleshoot_test_README.md.

digraph troubleshoot_test_diagnose_only {
    graph [ label="Troubleshoot test: Diagnose reports on a fail that needs operator judgement" ];

    start        [shape=Mdiamond, label="Start"];
    setup        [shape=parallelogram, label="Setup",
                  command="echo setup ok"];
    needs_human  [shape=parallelogram, label="Needs human judgement (exits 42)",
                  command="echo 'This task requires operator review' >&2; exit 42"];
    finalize     [shape=parallelogram, label="Will not run under Diagnose",
                  command="echo resumed cleanly"];
    exit         [shape=Msquare, label="Done"];

    start -> setup -> needs_human -> finalize -> exit;
}
)TEMPLATE";

const char* const kTpl_troubleshoot_test_full_missing_tool =
R"TEMPLATE(// Troubleshoot test fixture — Full tier
//
// Failure shape:  SelfExitError (or "command not found") because the stage
//                 calls a binary that is not on PATH for most operators
//                 (`jq`, here, used as a deliberately-recognisable stand-in).
// Expected fix:   Full agent's allow-list permits `Bash(npm install:*)` /
//                 `Bash(pip install:*)` etc. — it should either replace the
//                 missing-tool call with a portable equivalent (`python -c`,
//                 `sed`, `awk`), OR (if the operator wants to test the
//                 dependency-install path) install the tool with `brew
//                 install jq` / `apt-get install jq` and retry.
//                 In practice the substitute-with-portable-equivalent fix is
//                 the safer demo: it doesn't mutate the operator's
//                 environment.
// Definition of success: run resumes past parse_json; finalize echoes
//                 "resumed cleanly".
//
// Drive it: see README troubleshoot_test_README.md.

digraph troubleshoot_test_full_missing_tool {
    graph [ label="Troubleshoot test: Full broadens the allow-list to fix or substitute a missing tool" ];

    start       [shape=Mdiamond, label="Start"];
    setup       [shape=box, type="tool", label="Setup",
                 command="echo setup ok"];
    parse_json  [shape=box, type="tool", label="Uses jq — agent should substitute or install",
                 command="echo '{\"answer\":42}' | jq -r .answer"];
    finalize    [shape=box, type="tool", label="Finalize",
                 command="echo resumed cleanly"];
    exit        [shape=Msquare, label="Done"];

    start -> setup -> parse_json -> finalize -> exit;
}
)TEMPLATE";

const char* const kTpl_troubleshoot_test_tweak_timeout =
R"TEMPLATE(// Troubleshoot test fixture — Tweak tier
//
// Failure shape:  WallClockWithoutOwnProgress (timeout)
// Expected fix:   Tweak agent edits the `timeout` attribute on slow_op
//                 to give it more headroom, then `needle stage retry:slow_op`.
// Definition of success: the run resumes past slow_op and finalize executes,
//                 leaving "resumed cleanly" in the run log.
//
// Drive it:
//   1. Start `needle serve`.
//   2. From the dashboard, click "Run" on this file.
//   3. In the new-run modal, set "Troubleshoot mode on failure" = Tweak.
//   4. Watch the troubleshoot tile attach when slow_op times out.

digraph troubleshoot_test_tweak_timeout {
    graph [ label="Troubleshoot test: Tweak fixes a too-short timeout" ];

    start    [shape=Mdiamond, label="Start"];
    setup    [shape=parallelogram, label="Setup",
              command="echo setup ok"];
    slow_op  [shape=parallelogram, label="Slow op (1s timeout, sleeps 5s)",
              command="sleep 5 && echo done",
              timeout="1s"];
    finalize [shape=parallelogram, label="Finalize",
              command="echo resumed cleanly"];
    exit     [shape=Msquare, label="Done"];

    start -> setup -> slow_op -> finalize -> exit;
}
)TEMPLATE";

const char* const kTpl_troubleshoot_test_tweak_typo =
R"TEMPLATE(// Troubleshoot test fixture — Tweak tier
//
// Failure shape:  SelfExitError — command not found
// Expected fix:   Tweak agent edits `command="ehco …"` → `command="echo …"`
//                 in this DOT, then `needle stage retry:say_hello`.
// Definition of success: run resumes past say_hello; finalize echoes
//                 "resumed cleanly".
//
// Drive it: see README troubleshoot_test_README.md.

digraph troubleshoot_test_tweak_typo {
    graph [ label="Troubleshoot test: Tweak fixes a command typo" ];

    start      [shape=Mdiamond, label="Start"];
    setup      [shape=parallelogram, label="Setup",
                command="echo setup ok"];
    say_hello  [shape=parallelogram, label="Typo on purpose: 'ehco' instead of 'echo'",
                command="ehco 'hello from needle'"];
    finalize   [shape=parallelogram, label="Finalize",
                command="echo resumed cleanly"];
    exit       [shape=Msquare, label="Done"];

    start -> setup -> say_hello -> finalize -> exit;
}
)TEMPLATE";

struct Entry { const char* name; const char* content; };
const Entry kEntries[] = {
    { "goal_gate", kTpl_goal_gate },
    { "human_gate", kTpl_human_gate },
    { "interactive_chat", kTpl_interactive_chat },
    { "multi_backend", kTpl_multi_backend },
    { "parallel_pipeline", kTpl_parallel_pipeline },
    { "reference_template", kTpl_reference_template },
    { "simple_pipeline", kTpl_simple_pipeline },
    { "troubleshoot_test_diagnose_only", kTpl_troubleshoot_test_diagnose_only },
    { "troubleshoot_test_full_missing_tool", kTpl_troubleshoot_test_full_missing_tool },
    { "troubleshoot_test_tweak_timeout", kTpl_troubleshoot_test_tweak_timeout },
    { "troubleshoot_test_tweak_typo", kTpl_troubleshoot_test_tweak_typo },
};
const std::size_t kEntriesCount = 11;

} // anonymous namespace

std::vector<std::string> list_names() {
    std::vector<std::string> out;
    out.reserve(kEntriesCount);
    for (std::size_t i = 0; i < kEntriesCount; ++i) {
        out.emplace_back(kEntries[i].name);
    }
    return out;
}

const char* get(const std::string& name) {
    for (std::size_t i = 0; i < kEntriesCount; ++i) {
        if (name == kEntries[i].name) return kEntries[i].content;
    }
    return nullptr;
}

} // namespace templates
} // namespace needle
