#!/usr/bin/env python3
"""Embed docs/dot-authoring-rules.md as a C++ string constant.

Reads docs/dot-authoring-rules.md and writes
src/server/dot_authoring_rules_embedded.cpp, which exposes
needle::rules::kDotAuthoringRules to consumers in dot_generator.cpp
and the `needle dot-rules` CLI subcommand.

The generated file is checked in so builds without Python3 still work;
CMake regenerates it when the source markdown changes.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "dot-authoring-rules.md"
OUTPUT = ROOT / "src" / "server" / "dot_authoring_rules_embedded.cpp"

text = SOURCE.read_text(encoding="utf-8")

# Avoid clashing with the raw-string-literal delimiter `RULES`.
escaped = text.replace(")RULES", ") RULES")

OUTPUT.write_text(
    "// Generated by scripts/embed_rules.py — do not edit by hand.\n"
    "#include \"needle/rules/dot_authoring_rules.h\"\n\n"
    "namespace needle {\nnamespace rules {\n\n"
    "const char* const kDotAuthoringRules =\n"
    "R\"RULES(" + escaped + ")RULES\";\n\n"
    "} // namespace rules\n} // namespace needle\n",
    encoding="utf-8",
)
