#!/usr/bin/env python3
"""Convert dashboard asset files into C++ string constants.

Reads:
    src/server/assets/dashboard.html
    src/server/assets/dashboard.css
    src/server/assets/dashboard.js

Writes:
    src/server/dashboard_html.cpp

The generated file exposes three string constants and an assemble_page()
function in namespace needle::dashboard.
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(REPO_ROOT, "src", "server", "assets")
OUTPUT_FILE = os.path.join(REPO_ROOT, "src", "server", "dashboard_html.cpp")

DELIMITER = "NEEDLE_RAW"


def read_asset(name):
    path = os.path.join(ASSETS_DIR, name)
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if DELIMITER in content:
        print(f"ERROR: asset {name} contains raw string delimiter '{DELIMITER}'", file=sys.stderr)
        sys.exit(1)
    return content


MAX_LITERAL_LEN = 60000  # Stay safely below C++ 65536 limit


def emit_string_const(out, name, content):
    """Emit a string constant, splitting into concatenated literals if too long."""
    if len(content) <= MAX_LITERAL_LEN:
        out.append(f'const char* const {name} = R"{DELIMITER}(')
        out.append(content)
        out.append(f'){DELIMITER}";')
    else:
        # Split into concatenated std::string from multiple raw string literals.
        # Split at line boundaries to avoid breaking tokens in the middle.
        lines = content.split('\n')
        chunks = []
        current_chunk = []
        current_len = 0
        for line in lines:
            line_with_nl = line + '\n'
            if current_len + len(line_with_nl) > MAX_LITERAL_LEN and current_chunk:
                chunks.append(''.join(current_chunk))
                current_chunk = []
                current_len = 0
            current_chunk.append(line_with_nl)
            current_len += len(line_with_nl)
        if current_chunk:
            # Remove trailing newline from last chunk if content didn't end with one
            last = ''.join(current_chunk)
            if not content.endswith('\n'):
                last = last.rstrip('\n')
            chunks.append(last)

        out.append(f'static const std::string {name}_storage =')
        for i, chunk in enumerate(chunks):
            if i == 0:
                out.append(f'    std::string(R"{DELIMITER}(')
                out.append(chunk)
                if len(chunks) == 1:
                    out.append(f'){DELIMITER}");')
                else:
                    out.append(f'){DELIMITER}")')
            else:
                out.append(f'    + R"{DELIMITER}(')
                out.append(chunk)
                if i == len(chunks) - 1:
                    out.append(f'){DELIMITER}";')
                else:
                    out.append(f'){DELIMITER}"')
        out.append(f'const char* const {name} = {name}_storage.c_str();')


def main():
    css = read_asset("dashboard.css")
    html = read_asset("dashboard.html")
    js = read_asset("dashboard.js")

    out = []
    out.append("// Generated by scripts/embed_html.py — do not edit by hand.")
    out.append("// Re-generate: python3 scripts/embed_html.py")
    out.append("")
    out.append('#ifdef NEEDLE_ENABLE_SERVER')
    out.append("")
    out.append('#include "needle/server/dashboard_html.h"')
    out.append('#include "needle/util/graph_serializer.h"')
    out.append('#include <string>')
    out.append("")
    out.append("namespace needle { namespace dashboard {")
    out.append("")
    emit_string_const(out, "CSS", css)
    out.append("")
    emit_string_const(out, "HTML", html)
    out.append("")
    emit_string_const(out, "JS", js)
    out.append("")
    out.append("std::string assemble_page(const std::string& graph_svg,")
    out.append("                          const std::string& graph_name) {")
    out.append('    std::string page = "<!DOCTYPE html>\\n<html>\\n<head>\\n"')
    out.append('        "<meta charset=\\"utf-8\\">\\n"')
    out.append('        "<meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1\\">\\n"')
    out.append('        "<title>needle</title>\\n"')
    out.append('        "<style>\\n";')
    out.append("    page += CSS;")
    out.append('    page += "\\n</style>\\n</head>\\n<body>\\n";')
    out.append("    page += HTML;")
    out.append("")
    out.append("    // Replace {{GRAPH_SVG}} placeholder")
    out.append('    std::string svg_token = "{{GRAPH_SVG}}";')
    out.append("    auto pos = page.find(svg_token);")
    out.append("    if (pos != std::string::npos) {")
    out.append("        page.replace(pos, svg_token.size(), graph_svg);")
    out.append("    }")
    out.append("")
    out.append("    // Replace {{GRAPH_NAME}} placeholder")
    out.append('    std::string name_token = "{{GRAPH_NAME}}";')
    out.append("    pos = page.find(name_token);")
    out.append("    if (pos != std::string::npos) {")
    out.append("        page.replace(pos, name_token.size(), html_escape(graph_name));")
    out.append("    }")
    out.append("")
    out.append('    page += "\\n<script>\\n";')
    out.append("    page += JS;")
    out.append('    page += "\\n</script>\\n</body>\\n</html>\\n";')
    out.append("    return page;")
    out.append("}")
    out.append("")
    out.append("}} // namespace needle::dashboard")
    out.append("")
    out.append("#endif // NEEDLE_ENABLE_SERVER")
    out.append("")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"Generated {OUTPUT_FILE}")
    print(f"  CSS: {len(css)} bytes")
    print(f"  HTML: {len(html)} bytes")
    print(f"  JS: {len(js)} bytes")


if __name__ == "__main__":
    main()
