#!/usr/bin/env python3
"""Embed sample_dots/*.dot as C++ string constants.

Reads every *.dot file under sample_dots/ and writes
src/server/templates_embedded.cpp, which implements
needle::templates::list_names() and needle::templates::get().

The generated file is checked in so builds without Python3 still work;
CMake regenerates it when any sample DOT changes.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "sample_dots"
OUTPUT = ROOT / "src" / "server" / "templates_embedded.cpp"


def escape_raw(content: str) -> str:
    # Raw-string-literal delimiter conflict prevention. Should never
    # happen for hand-authored DOT files but be defensive.
    return content.replace(")TEMPLATE", ") TEMPLATE")


def main() -> int:
    if not SOURCE_DIR.is_dir():
        OUTPUT.write_text(_empty_cpp(), encoding="utf-8")
        return 0

    templates = sorted(SOURCE_DIR.glob("*.dot"))
    lines = [
        "// Generated by scripts/embed_templates.py — do not edit by hand.",
        "#include \"needle/rules/templates.h\"",
        "",
        "#include <cstring>",
        "",
        "namespace needle {",
        "namespace templates {",
        "namespace {",
        "",
    ]

    for path in templates:
        name = path.stem
        ident = "kTpl_" + name.replace("-", "_").replace(".", "_")
        content = escape_raw(path.read_text(encoding="utf-8"))
        lines.append(
            f"const char* const {ident} =\n"
            f'R"TEMPLATE({content})TEMPLATE";'
        )
        lines.append("")

    lines.append("struct Entry { const char* name; const char* content; };")
    lines.append("const Entry kEntries[] = {")
    for path in templates:
        name = path.stem
        ident = "kTpl_" + name.replace("-", "_").replace(".", "_")
        lines.append(f'    {{ "{name}", {ident} }},')
    lines.append("};")
    lines.append(f"const std::size_t kEntriesCount = {len(templates)};")
    lines.append("")
    lines.append("} // anonymous namespace")
    lines.append("")
    lines.append("std::vector<std::string> list_names() {")
    lines.append("    std::vector<std::string> out;")
    lines.append("    out.reserve(kEntriesCount);")
    lines.append("    for (std::size_t i = 0; i < kEntriesCount; ++i) {")
    lines.append("        out.emplace_back(kEntries[i].name);")
    lines.append("    }")
    lines.append("    return out;")
    lines.append("}")
    lines.append("")
    lines.append("const char* get(const std::string& name) {")
    lines.append("    for (std::size_t i = 0; i < kEntriesCount; ++i) {")
    lines.append("        if (name == kEntries[i].name) return kEntries[i].content;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace templates")
    lines.append("} // namespace needle")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


def _empty_cpp() -> str:
    return (
        "// Generated by scripts/embed_templates.py — sample_dots/ not present.\n"
        "#include \"needle/rules/templates.h\"\n\n"
        "namespace needle {\nnamespace templates {\n\n"
        "std::vector<std::string> list_names() { return {}; }\n"
        "const char* get(const std::string&) { return nullptr; }\n\n"
        "} // namespace templates\n} // namespace needle\n"
    )


if __name__ == "__main__":
    raise SystemExit(main())
